[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
remappings = []
solc = '0.8.24'
evm_version = 'paris'
fs_permissions = [{ access = "read", path = "./" }]


[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
optimismGoerli = "${OPTIMISM_GOERLI_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
polygonMumbai = "${POLYGON_MUMBAI_RPC_URL}"
bnbChainTestnet = "${BNB_CHAIN_TESTNET_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
metisSepolia = "${METIS_SEPOLIA_RPC_URL}"
zksyncSepolia = "${ZKSYNC_SEPOLIA_RPC_URL}"
scrollSepolia = "${SCROLL_SEPOLIA_RPC_URL}"
zircuitSepolia = "${ZIRCUIT_SEPOLIA_RPC_URL}"
xlayerSepolia = "${XLAYER_SEPOLIA_RPC_URL}"
polygonZkevmSepolia = "${POLYGON_ZKEVM_SEPOLIA_RPC_URL}"
polkadotAstarShibuya = "${POLKADOT_ASTAR_SHIBUYA_RPC_URL}"
mantleSepolia = "${MANTLE_SEPOLIA_RPC_URL}"
soneiumMinatoSepolia = "${SONEIUM_MINATO_SEPOLIA_RPC_URL}"
bsquaredTestnet = "${BSQUARED_TESTNET_RPC_URL}"
bobSepolia = "${BOB_SEPOLIA_RPC_URL}"
worldchainSepolia = "${WORLDCHAIN_SEPOLIA_RPC_URL}"
shibariumTestnet = "${SHIBARIUM_TESTNET_RPC_URL}"
bitlayerTestnet = "${BITLAYER_TESTNET_RPC_URL}"
fantomSonicTestnet = "${FANTOM_SONIC_TESTNET_RPC_URL}"
cornTestnet = "${CORN_TESTNET_RPC_URL}"
hashkeySepolia = "${HASHKEY_SEPOLIA_RPC_URL}"
inkSepolia = "${INK_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHEREUM_SEPOLIA_API_KEY}" }
optimismGoerli = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
avalancheFuji = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
arbitrumSepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
polygonMumbai = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
baseSepolia = { key = "${BASE_SEPOLIA_API_KEY}" }
zksyncSepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
scrollSepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
zircuitSepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
xlayerSepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
mantleSepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
soneiumMinatoSepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
bobSepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
worldchainSepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
shibariumTestnet = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
inkSepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.uniswap]
solc-version = "0.7.6"